### ISSUE TITLE
Having issues in merging branches.

### ISSUE THREAD

**Issue by amisha-chauhan** [codewayy/github_series-2#12]
I am having some issues in merging branches. The image below shows the issue i am facing.

![Screenshot (141)](https://user-images.githubusercontent.com/66894429/84859168-3aff3280-b08a-11ea-90d3-4b43f8e24549.png)

This is part of task-4 of git and github series in which we have to create a issue and add label as our name to it.

Amisha (@amisha-chauhan )
(@codewayy )

**Comment by codewayy** [comment]
You need to create a merge conflicts first. I can't see that in the above image. Please update it Amisha.

**Comment by amisha-chauhan** [comment]
#14
